import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class AssignmentCreate {
  @ApiProperty()
  task_id: number;
  @ApiProperty()
  assigned_to: string;
}

export class Assignment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  task_id: number;
  @ApiProperty()
  assigned_to: string;
}
